---
- hosts: all
  become: true
  tasks:
    - name: Install Apahe2
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes
    - name: Copy files
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html
        owner: root
        group: root
        mode: '0664'
    - name: Start server
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes
